spring:
  application:
    name: community
  config:
    import: optional:configserver:http://root:root@localhost:8888

#management:
#  endpoints:
#    enabled-by-default: false
#    web:
#      exposure:
#        include: refresh
#  endpoint:
#    refresh:
#      enabled: true